- name: Verify Windows version
  hosts: all
  tasks:
    - name: Check Windows version
      win_command: cmd /c ver
      register: win_version

    - name: Show version
      debug:
        var: win_version.stdout
