- name: Upgrade Windows 10 to Windows 11
  hosts: all
  gather_facts: no
  tasks:
    - name: Mount Windows 11 ISO
      win_command: PowerShell Mount-DiskImage -ImagePath "C:\ios\Win11.iso"

    - name: Run setup.exe from mounted ISO (assuming D:)
      win_command: E:\setup.exe /auto upgrade /quiet /noreboot /dynamicupdate disable

    - name: Reboot after upgrade
      win_reboot:
        reboot_timeout: 3600
   
