---
- name: Copy Windows 11 ISO and mount it
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy ISO to target
      win_copy:
        src: /ios/Win11.iso
        dest: C:\Temp\Win11.iso

    - name: Mount ISO
      win_shell: Mount-DiskImage -ImagePath "C:\Temp\Win11.iso"
      args:
        executable: powershell.exe
