- name: Upgrade Windows 10 to Windows 11
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure destination directory exists
      win_file:
        path: C:\ios\Win11
        state: directory


    - name: Run Windows 11 upgrade silently
      win_command: C:\ios\Win11\setup.exe /auto upgrade /quiet /noreboot /dynamicupdate disable

    - name: Reboot for installation
      win_reboot:
        reboot_timeout: 3600
