- name: Upgrade Windows 10 to Windows 11
  hosts: all
  gather_facts: false
  tasks:

    - name: Start silent upgrade
      win_command: >
        C:\ios\\Win11\setup.exe /auto upgrade /quiet /noreboot /dynamicupdate disable
      args:
        chdir: C:\Temp\Win11

    - name: Reboot the system
      win_reboot:
        reboot_timeout: 3600
