- name: Upgrade Windows 10 to 11 via SMB share
  hosts: all
  gather_facts: false
  tasks:
    - name: Map SMB share (C:) with credentials
      win_command: >
        net use C: \\172.23.18.207\ios\Win11 /user:jahangir Root@1234

    - name: Start upgrade from mounted drive
      win_command: C:\setup.exe /auto upgrade /quiet /noreboot /dynamicupdate disable

    - name: Reboot the system
      win_reboot:
        reboot_timeout: 3600

